from esphome.const import (
    DEVICE_CLASS_CURRENT,
    DEVICE_CLASS_FREQUENCY,
    DEVICE_CLASS_POWER,
    DEVICE_CLASS_PRESSURE,
    DEVICE_CLASS_TEMPERATURE,
    DEVICE_CLASS_VOLUME_FLOW_RATE,
    STATE_CLASS_MEASUREMENT,
    UNIT_AMPERE,
    UNIT_CELSIUS,
    UNIT_HERTZ,
    UNIT_WATT,
)

DEFAULT_UNITS = {
    DEVICE_CLASS_CURRENT: UNIT_AMPERE,
    DEVICE_CLASS_FREQUENCY: UNIT_HERTZ,
    DEVICE_CLASS_POWER: UNIT_WATT,
    DEVICE_CLASS_PRESSURE: "kgf/cm²",
    DEVICE_CLASS_TEMPERATURE: UNIT_CELSIUS,
    DEVICE_CLASS_VOLUME_FLOW_RATE: "L/min",
}
DEFAULT_STATE_CLASS = dict.fromkeys(
    DEFAULT_UNITS,
    STATE_CLASS_MEASUREMENT,
)
