name: Compilation check
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - wmbus
          - panasonic_aquarea
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Build firmware
        id: esphome_build
        uses: esphome/build-action@v8.0.0
        with:
          yaml-file: tests/${{ matrix.name }}.yaml
          version: "2026.7.3"
